# Generated by Django 3.2.16 on 2024-12-05 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20241205_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ('output_order', 'title'), 'verbose_name': 'Мороженое', 'verbose_name_plural': 'Мороженое'},
        ),
    ]
